permalink: /:year/:month/:day/:title.html
paginate: 10
gems: [jekyll-paginate]
markdown: kramdown

# 作者信息
author: 
  name: 付达贵
  email: 515416840@qq.com
  link: http://a4690619.github.io
  weibo: http://weibo.com/orangeissweet
  github: https://github.com/a4690619

# 站点信息
title: 启灵的博客
description: My personal blog
url: http://a4690619.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.jpg
favicon: /public/img/deer3.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档